# Generated by Django 2.2.2 on 2019-07-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateHome', '0002_sellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='propertyPrice',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
